
spring:
  application:
    name: "webapp"
  profiles:
    active: "prod"
  config:
    import: "optional:z-configserver:http://localhost8071/"

server:
  servlet:
    context-path: "/zoologia"
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"