server:
  port: 8073

spring:
  application:
    name: "appandcard"
  profiles:
    active: "prod"
  datasource:
    url: "jdbc:mysql://localhost:3306/zoologiav2"
    username: "root"
    password: "Yann*060103"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

#configration of actuator enpoint in eureka making info visible in eureka dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#info in eureka server dashboard
info:
  app:
    name: "appandcard"
    description: "zoologia Application"
    version: "1.0.0"
